### ISSUE TITLE
Sim Crash When UnregisterPrimitive Is Called

### ISSUE THREAD

**Issue by GeorgeBarlow** [Engin1980/FS2020EExtensions#1]
Hi,

Just saw your project as I was browsing through repos and it's really nice! I noticed that there is a possibility that when UnregisterPrimitive is called during the Close process of ESimConnect it can crash the sim. I believe this is due to MSFS still firing events during the ClearDataDefinition call. Asobo advises you that you temporarily suspend data events before sending the ClearDataDefinition call, however, I tried a quick implementation of this and still was having a few issues where the sim was continuing to crash. 

To increase the likelihood of reproducing this, changing the period to SIMCONNECT_PERIOD_SIM_FRAME or SIMCONNECT_PERIOD_VISUAL_FRAME should do the trick.

I'll try to look further into the cause but it feels like an endless battle with SimConnect to prevent issues like this from coming up.

Thanks,
George

**Comment by Engin1980** [comment]
Dear @GeorgeBarlow, thank you for your notice.

To be honest,the Chlaot-thing is still in development and the ESimConnect library is (shamefully) not tested for unregistering events or types. So far, I did always quit the whole application not taking into account any clean up at the exit.

I am aware ( = I have experienced too) such strange behavior. However, if you do some more tests and find anything useful, please post it here and I will extend the ESimConnect library to be more robust.

I'll keep this open for any potential updates.

Thanks again,
Marek

**Comment by GeorgeBarlow** [comment]
Of course, though I do feel like this issue goes beyond the scope of how 3rd parties interact with the library, there should be some sort of handling when these events arise. Therefore, I have asked on the MSFS DevSupport forums if this is something that is an issue with MSFS since I don't understand why the sim just CTDs, surely it should throw some sort of exception or indication of what went wrong. Nevertheless, I will try to report back any findings as it's something I'd like to see if I can get resolved. 

Thanks, 
George

**Comment by Engin1980** [comment]
Hello, @GeorgeBarlow, a quick remark in here I have just now realized - unregistering (of anything) causes sim crash to me if sim is in the main menu (or - maybe - not in the flight). Once in flight, unregistering works correctly.

I moved ESimConnect into a separate repo as I am using it in several other projects now, so if you are interested, you can check the behavior w.r.t. to that implementation: https://github.com/Engin1980/ESimConnect. Note this is only a basic implementation with no refactoring done yet.

**Comment by GeorgeBarlow** [comment]
Hey! 

<strike>I've just got around to testing your new implementation and I'm still facing the same CTD issue when unregistering the sim vars. I'm using MSFS (v1.37.12.0) aka the latest version of SU15 beta, so if it's working fine for you I assume it's related to the beta? However, I haven't heard anyone else report the same issue, though I can't see what is wrong with your implementation. It's really strange how it's causing a full title crash.</strike>

After some further testing, I believe I have identified the issue. ESimConnect is still receiving events for the registered sim vars from MSFS during the moment that you unregister them, causing undefined behaviour and resulting in a CTD. I have experimented with a potential solution and believe that something like the following could work:
```c#
public void StopReceivingData(int requestId, int typeId)
{
    logger.LogMethodStart();
    parent.EnsureConnected();

    EEnum eRequestId = (EEnum)requestId;
    EEnum etypeId = (EEnum)typeId;

    // Prevent data from being received in order to clear the definition
    parent.Try(() =>
        parent.simConnect!.RequestDataOnSimObject(
            eRequestId, etypeId, SimConnect.SIMCONNECT_OBJECT_ID_USER, SIMCONNECT_PERIOD.NEVER,
            SIMCONNECT_DATA_REQUEST_FLAG.DEFAULT, 0, 0, 0),
        ex => new InternalException($"Failed to invoke 'RequestDataOnSimObject(...)'.", ex));

    logger.LogMethodEnd();
}
```
Please note that the above is merely a draft implementation, but the principle remains the same. By ensuring that we set each request period to `NEVER` prior to running unregister, we can prevent MSFS from pushing data on a definition that no longer exists.

Additionally, after speaking to some people who have more experience with SimConnect than I do (and this is something you're probably already aware of), I've found that these functions run asynchronously. Therefore, it's best to avoid triggering them directly after one another, as it may take some time for the stream of data to stop, especially when using periods such as `SIM_VISUAL` instead of `SECOND`.

I'll keep testing to ensure that this does resolve the issue but, in my opinion, this is the only thing that would make logical sense as to why there are still CTDs. It is also mentioned in the SDK documentation for [ClearDataDefinition](https://docs.flightsimulator.com/html/Programming_Tools/SimConnect/API_Reference/Events_And_Data/SimConnect_ClearDataDefinition.htm), in the remarks section (albeit not well highlighted in my opinion) that we should be ceasing all data requests prior to `ClearDataDefinition` gets called.

Hopefully this is the last of that issue.

**Comment by Engin1980** [comment]
Well, excelent work, I have to say!

I have implemented a simple test of that - see `https://github.com/Engin1980/ESimConnect/tree/unregisterStabilityTest` and `https://github.com/Engin1980/ESimConnect/blob/unregisterStabilityTest/ESimConnectTest/Tests/RegisterUnregisterTest.cs` testing class, where I am trying to overstress the system with repeated registrations/unregistrations and it seems to be stable. To enable "CTD", just revert to old behavior using `simCon.Values.UnregisterSafely(...)   ==> ... .Unregister(...)` (line 89) and it immediatelly crashes.

Can you please check, if it behaves correctly for your?

If so, I'll somehow implement the delay for unregistering in the library.

And again, thank you :-) Great work.

**Comment by GeorgeBarlow** [comment]
Thank you, it was annoying me a lot since it didn't feel right just not unregistering sim variables to avoid having crashes (which I believe caused more issues in itself). I've just tried your `UnregisterSafely` function and it seems to do the trick!

That was my next thing to take a look at. Let me know how you get on with the implementation, I'll try looking out for it :) 

Likewise, really like the library as a whole, has a very nice structure to it :)

**Comment by Engin1980** [comment]
Ok, I have rewritten the whole stuff out of this project to a separate ESimConnect repo mentioned above. It seems to be working.
Therefore, closing this issue. Thank you once more for your help.
